site_name: imgmaker
site_description: Create high-quality images programmatically using easily-hackable templates.
site_author: Max Woolf (@minimaxir)

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Create Your Own Template: template.md
  - Templates:
      - Hero: hero.md
      - Meme (Image Macro): meme.md
      - Watermarked Image: watermark.md
  - Helpful Notes: helpful-notes.md

theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Source Sans Pro"
    code: "Fira Code"
  icon:
    logo: fontawesome/brands/git-alt

repo_name: minimaxir/imgmaker
repo_url: https://github.com/minimaxir/imgmaker
edit_uri: ""

copyright: "Copyright &copy; 2020 Max Woolf"

extra:
  social:
    - type: "github"
      link: "https://github.com/minimaxir/imgmaker"
    - type: "twitter"
      link: "https://twitter.com/minimaxir"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc
  - admonition
  - toc:
      permalink: true
